# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WordNet-BestStem
version:      0.2.1
version_from: BestStem.pm
installdirs:  site
requires:
    WordNet::QueryData:            0
    WordNet::Similarity::ICFinder: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
